class CONFIGURATION:
    SECRET_KEY = 'uzE7lSw8Ch7X4aB81E22Z6Nh'
    JSON_AS_ASCII = False,
    MAIL_SERVER='smtp.yandex.ru',
    MAIL_USERNAME='mevomsngr',
    MAIL_PASSWRD='uzE7lSw8Ch7X4aB81E22Z6Nh',
    MAIL_PORT=465,
    MAIL_USE_SSL=True,
    MAIL_USE_TLS=False,